#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -O3 -Weverything -Wno-poison-system-directories sun.c -o out

elif [ "clean" = "$1" ]; then
	rm -rf out
	rm -rf out.dSYM

elif [ "" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-poison-system-directories -fsanitize=address,undefined sun.c -o out
else 
	echo "build: unknown target: $1"
fi
