#!/bin/zsh


if [ "release" = "$1" ]; then
	clang -Ofast e.c -o run


elif [ "clean" = "$1" ]; then
	rm -rf run
	rm -rf run.dSYM

elif [ "" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-declaration-after-statement -Wno-deprecated-declarations -fsanitize=address,undefined e.c -o run -ferror-limit=4


elif [ "fuzz" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-declaration-after-statement -fsanitize=fuzzer,address,undefined,leak e.c -o run

else 
	echo "build: unknown target: $1"
fi
