#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -Ofast c.c -o run


elif [ "small" = "$1" ]; then
	clang -Os c.c -o run	


elif [ "clean" = "$1" ]; then
	rm -rf run
	rm -rf run.dSYM
	rm -rf c.plist

elif [ "" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-poison-system-directories -Wno-declaration-after-statement -fsanitize=address,undefined c.c -o run -ferror-limit=4

elif [ "check" = "$1" ]; then 
	clang -Weverything --analyze -Wno-declaration-after-statement -Wno-poison-system-directories c.c


else 
	echo "build: unknown target: $1"
fi
