#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -Ofast c.c -o editor


elif [ "small" = "$1" ]; then
	clang -Os c.c -o editor	


elif [ "clean" = "$1" ]; then
	rm -rf editor
	rm -rf editor.dSYM
	rm -rf c.plist

elif [ "" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-declaration-after-statement -fsanitize=address,undefined c.c -o editor -ferror-limit=1

elif [ "check" = "$1" ]; then 
	clang -Weverything --analyze -Wno-declaration-after-statement -Wno-poison-system-directories c.c


else 
	echo "build: unknown target: $1"
fi


