


// uint8_t r = bcm2835_i2c_read(buffer, buffer_length);


// enum SSD1306_commands {
// 	SET_CONTRAST = 0x81, // requires: arg[0]:u8

// 	SET_FOLLOW_RAM_CONTENTS = 0xA4,
// 	SET_ENTIRE_DISPLAY_ON = 0xA5,

// 	SET_NORMAL = 0xA6,
// 	SET_INVERSION = 0xA7,

// 	SET_DISPLAY_ON = 0xAF,
// 	SET_DISPLAY_OFF = 0xAE,

// 	SET_MEMORY_ADDRESS = 0x20,
// 	SET_COLUMN_ADDRESS = 0x21,
// 	SET_PAGE_ADDRESS = 0x22,

// 	SET_DISPLAY_START_LINE = 0x40,

// 	SET_SEG_REMAP = 0xA0,
// 	SET_MULTIPLEX_RATIO = 0xA8,
// 	SET_COM_OUT_DIR = 0xC0,
// 	SET_DISPLAY_OFFSET = 0xD3,
// 	SET_COM_PIN_CONFIG = 0xDA,
// 	SET_DISP_CLOCK_DIV = 0xD5,
// 	SET_PRECHARGE = 0xD9,
// 	SET_VCOM_DESEL = 0xDB,
// 	SET_CHARGE_PUMP = 0x8D,
// };